# Generated by Django 4.0.4 on 2022-04-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_poll_question_text_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesomeanswer',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_answer',
        ),
        migrations.DeleteModel(
            name='ChoiceAnswer',
        ),
        migrations.DeleteModel(
            name='ChoiceSomeAnswer',
        ),
    ]
