# Generated by Django 4.0.4 on 2022-04-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_choicesomeanswer_poll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('answer_with_text', 'Answer with text'), ('answer_with_choice', 'Answer with choice'), ('answer_with_some_choices', 'Answer with some choices')], max_length=25, verbose_name='Type of question'),
        ),
    ]
